### ISSUE TITLE
USB OTG dont work

### ISSUE THREAD

**Issue by hemetz** [Euphoria-OS/Bug-tracker#11]
Your device: Nexus 6 (shamu)

Which ROM version are you using? (provide download link)
http://euphoria-os.ninja/download.php?file=Nexus%206/Nexus%206%20Builds/Euphoria-OS-1.1-shamu-OFFICIAL-20150512.zip

What kernel are you using - included in the ROM or from another source?
(provide xda/download link)
stock from ROM

What steps will reproduce the problem?
1. open the storage settings
2. plugin OTG drive (FAT32) 
3.

What is the expected result? What do you see instead?
i would expect that i could mount the USB drive now, but the usb setting still grayed out. 

Is the result seen after a clean flash too?
yes

Attach a logcat and/or a last_kmsg . Without this,the issue is impossible
to fix.
cant find last_kmsg! is it gone with Lollipop? but dosnt matter: no kernel crash.
i will add the logcat when im at home

Update: [Logcat](https://drive.google.com/file/d/0B-ICdabLzTj6MlpfT2t0RzZ0a1k/view?usp=sharing)

**Comment by dsmitty166** [comment]
I'm compiling a test build right now

**Comment by hemetz** [comment]
Greate, if you want I could test it.
Am 21.05.2015 3:16 vorm. schrieb "David Smit" notifications@github.com:

**Comment by hemetz** [comment]
Hi David,

mounting an otg works fine now.

At my first try I got an java io exception. I grabbed the logcat if you
want take a look, but after disconnect and reconnect the stick, it works
flawless.
Navigate through folders, create folders/files and delete them, works as
expected.

Thank you
Stefan

Greate, if you want I could test it.
Am 21.05.2015 3:16 vorm. schrieb "David Smit" notifications@github.com:

> I'm compiling a test build right now
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Euphoria-OS/Bug-tracker/issues/11#issuecomment-104087246
> .

05-22 04:12:37.432 W/ResourceType(2442): No package identifier when getting value for resource number 0x00000000
05-22 04:12:37.432 W/PackageManager(2442): Failure retrieving resources for com.nolanlawson.logcat: Resource ID #0x0
05-22 04:12:38.482 W/ResourceType(2442): No package identifier when getting value for resource number 0x00000000
05-22 04:12:38.482 W/PackageManager(2442): Failure retrieving resources for com.nolanlawson.logcat: Resource ID #0x0
05-22 04:12:38.924 W/        (14060): Zip: read 65557 failed: I/O error
05-22 04:12:38.924 W/zipro   (14060): Error opening archive /storage/usbdisk/com.google.android.gm.exchange-6.5-1533254-500065-minAPI14.apk: I/O Error
05-22 04:12:39.216 W/TRThreadPoolExecutor(3534): Task "p[Get token]" is a o. Failures of FutureTask can not be detected and exceptions will not be propagated by the executor
05-22 04:12:39.217 W/CronetSyncConnectionRcs(3534): Upload content type not set.
05-22 04:12:42.288 E/AmanattoDataUpdaterHelper(2601): Failed to get contextual suggestions.
05-22 04:12:42.289 E/AmanattoDataUpdaterHelper(2601): package name: pl.solidexplorer
05-22 04:12:42.370 W/        (14060): Zip: read 65557 failed: I/O error
05-22 04:12:42.371 W/zipro   (14060): Error opening archive /storage/usbdisk/com.google.android.gm.exchange-6.5-1533254-500065-minAPI14.apk: I/O Error
05-22 04:12:44.408 W/System.err(14060): pl.solidexplorer.ab: java.io.IOException: open failed: EIO (I/O error)
05-22 04:12:44.408 W/System.err(14060):     at pl.solidexplorer.FileExplorer.a.k(SourceFile:327)
05-22 04:12:44.408 W/System.err(14060):     at pl.solidexplorer.l.run(SourceFile:837)
05-22 04:12:44.408 W/System.err(14060): Caused by: java.io.IOException: open failed: EIO (I/O error)
05-22 04:12:44.408 W/System.err(14060):     at java.io.File.createNewFile(File.java:941)
05-22 04:12:44.408 W/System.err(14060):     at pl.solidexplorer.FileExplorer.a.createNewFile(SourceFile:448)
05-22 04:12:44.408 W/System.err(14060):     at pl.solidexplorer.FileExplorer.a.k(SourceFile:320)
05-22 04:12:44.408 W/System.err(14060):     ... 1 more
05-22 04:12:44.408 W/System.err(14060): Caused by: android.system.ErrnoException: open failed: EIO (I/O error)
05-22 04:12:44.408 W/System.err(14060):     at libcore.io.Posix.open(Native Method)
05-22 04:12:44.409 W/System.err(14060):     at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
05-22 04:12:44.409 W/System.err(14060):     at java.io.File.createNewFile(File.java:934)
05-22 04:12:44.409 W/System.err(14060):     ... 3 more
05-22 04:12:44.608 W/        (14060): Zip: read 65557 failed: I/O error
05-22 04:12:44.608 W/zipro   (14060): Error opening archive /storage/usbdisk/com.google.android.gm.exchange-6.5-1533254-500065-minAPI14.apk: I/O Error
05-22 04:12:46.238 E/WifiStateMachine(948): WifiStateMachine CMD_START_SCAN source -2 txSuccessRate=2,25 rxSuccessRate=6,72 targetRoamBSSID=any RSSI=-74
05-22 04:12:46.238 E/WifiStateMachine(948): WifiStateMachine starting scan for "Baresch"WPA_PSK with 2412,5180
05-22 04:12:47.079 E/WifiStateMachine(948): WifiStateMachine CMD_START_SCAN source 10124 txSuccessRate=0,28 rxSuccessRate=1,34 targetRoamBSSID=any RSSI=-78
05-22 04:12:49.187 W/IInputConnectionWrapper(14060): showStatusIcon on inactive InputConnection
05-22 04:12:50.176 W/ResourceType(2442): No package identifier when getting value for resource number 0x00000000
05-22 04:12:50.176 W/PackageManager(2442): Failure retrieving resources for pl.solidexplorer: Resource ID #0x0
