### ISSUE TITLE
"Charge only" setting doesn't works

### ISSUE THREAD

**Issue by turnoffer** [Euphoria-OS/Bug-tracker#13]
Nexus 4 (mako)
ROM version: [Euphoria-OS-1.1-mako-OFFICIAL-20150514](https://www.androidfilehost.com/?fid=23991606952603791), downloaded from [XDA](http://forum.xda-developers.com/nexus-4/development/rom-euphoria-os-1-0-t2997338)

Using kernel included in the ROM.

What steps will reproduce the problem?
1. Entering Settings - Storage - USB computer connection;
2. Turn on "Charge only", "MTP" automatically turns off;
3. Re-enter to the USB computer connection menu and seeing that "Charge only" is back to off and "MTP" is on;
4. Turn "Charge only" on, plug in data cable and settings sets back - "Charge only" to off and "MTP" to on;
5. Repeat randomly.

What is the expected result: charging phone via cable without data transfer.
What do I see instead: settings sets back while re-entering settings menu or with plug-in cable.

Attaches:
[logcat](https://www.dropbox.com/s/boyuzaqjzt7cw2k/logcat.log?dl=0)
[last_kmsg](https://www.dropbox.com/s/gnfggkh6b42uu7m/last_kmsg.log?dl=0)
[whole bugreport](https://www.dropbox.com/s/oow4oen848ykuan/bugreport.zip?dl=0)
[video demonstration - screen record](https://youtu.be/IVTtcpWFPlo) 
_P.S. Sorry about russian menu in video and my bad English ;)_

**Comment by dexmc** [comment]
Acknowledged. Thanks for the report.

**Comment by turnoffer** [comment]
I repeated all steps above on updated 1.1-mako-OFFICIAL-20150528 (which removed xposed as well) with same result. Just for info.

**Comment by Altaf-Mahdi** [comment]
Fixed http://eosgerrit.ddns.net:51250/#/c/6139/
