### ISSUE TITLE
No title in battery stats item

### ISSUE THREAD

**Issue by eurochild-dps** [Euphoria-OS/Bug-tracker#14]
nexus 4 latest official build

![screenshot_2015-06-02-21-04-29](https://cloud.githubusercontent.com/assets/7645326/7943136/558aa4f2-096b-11e5-9856-ee7cc94a44ee.png)

![screenshot_2015-06-02-21-05-06](https://cloud.githubusercontent.com/assets/7645326/7943135/558a1faa-096b-11e5-9fc4-b6ffcd5c62f4.png)

**Comment by dexmc** [comment]
confirmed. @Altaf-Mahdi can you take a look please

**Comment by Altaf-Mahdi** [comment]
I had this too but its gone now, I'm sure its cyanogenmod.platform app

**Comment by eurochild-dps** [comment]
![screenshot_2015-06-05-20-51-41](https://cloud.githubusercontent.com/assets/7645326/8011845/25879f24-0bc5-11e5-9b4c-7f713b04bba9.png)

![screenshot_2015-06-05-20-52-07](https://cloud.githubusercontent.com/assets/7645326/8011846/2589da1e-0bc5-11e5-8ff9-2854bf8859dc.png)

![screenshot_2015-06-05-20-52-31](https://cloud.githubusercontent.com/assets/7645326/8011847/258c7d32-0bc5-11e5-8264-deff6af7e544.png)

**Comment by dexmc** [comment]
@Altaf-Mahdi more instances of this bug. http://forum.xda-developers.com/showpost.php?p=61211421&postcount=1620
http://forum.xda-developers.com/showpost.php?p=61197287&postcount=1607

**Comment by Altaf-Mahdi** [comment]
This should fix the issue https://github.com/Euphoria-OS/android_packages_apps_Settings/commit/b0b74b4e53e7b1f189714885d6bfc988788e39c4
