### ISSUE TITLE
system UI crashes Nexus 4

### ISSUE THREAD

**Issue by andrerodrigues86** [Euphoria-OS/Bug-tracker#17]
Sometimes, when double touching to wake up device, I get sistem UI crash message. This only seems to happen when battery saver is enabled. It doesnt always happen.
Clean install, latest build. No exposed.

6-10 14:00:58.871 E/WifiStateMachine(560): WifiStateMachine CMD_START_SCAN source -2 txSuccessRate=0,75 rxSuccessRate=0,49 targetRoamBSSID=any RSSI=-49
06-10 14:01:05.333 V/WindowManager(560): Adding window Window{4a8eccd u0 AtchDlg:com.nolanlawson.logcat/com.nolanlawson.logcat.LogcatActivity} at 7 of 13 (after Window{2b5d111b u0 AtchDlg:com.nolanlawson.logcat/com.nolanlawson.logcat.LogcatActivity EXITING})
06-10 14:01:05.338 W/InputMethodManagerService(560): Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@27a17982 attribute=null, token = android.os.BinderProxy@10a2e753
06-10 14:01:05.389 I/ValidateNoPeople(560): skipping global notification
06-10 14:01:07.897 V/WindowManager(560): Adding window Window{207320d0 u0 AtchDlg:com.nolanlawson.logcat/com.nolanlawson.logcat.LogcatActivity} at 7 of 13 (after Window{4a8eccd u0 AtchDlg:com.nolanlawson.logcat/com.nolanlawson.logcat.LogcatActivity EXITING})
06-10 14:01:07.901 W/InputEventReceiver(7366): Attempted to finish an input event but the input event receiver has already been disposed.
06-10 14:01:07.903 W/InputMethodManagerService(560): Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@15e488c9 attribute=null, token = android.os.BinderProxy@10a2e753
06-10 14:01:08.373 I/ValidateNoPeople(560): skipping global notification
06-10 14:01:09.084 W/InputMethodManagerService(560): Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@871abce attribute=null, token = android.os.BinderProxy@10a2e753
06-10 14:01:09.503 I/ActivityManager(560): Killing 1251:com.google.android.gms.wearable/u0a18 (adj 15): empty #17
06-10 14:01:09.604 W/TRThreadPoolExecutor(1717): Task "NotifyOnDoneFutureTask[refresh_search_history]" is a x. Failures of FutureTask can not be detected and exceptions will not be propagated by the executor
06-10 14:01:09.616 W/TRThreadPoolExecutor(1717): Task "b[Get cookie call]" is a o. Failures of FutureTask can not be detected and exceptions will not be propagated by the executor
06-10 14:01:09.628 I/Icing   (1662): Usage reports 1 indexed 0 rejected 0 imm upload true
06-10 14:01:10.317 W/ResourceType(9654): No package identifier when getting value for resource number 0x00000000
06-10 14:01:10.317 W/PackageManager(9654): Failure retrieving resources for com.nolanlawson.logcat: Resource ID #0x0
06-10 14:01:16.037 W/TRThreadPoolExecutor(1717): Task "NotifyOnDoneFutureTask[log_attempted_searches_to_kansas]" is a x. Failures of FutureTask can not be detected and exceptions will not be propagated by the executor
06-10 14:01:18.426 I/ValidateNoPeople(560): skipping global notification
06-10 14:01:18.875 E/WifiStateMachine(560): WifiStateMachine CMD_START_SCAN source -2 txSuccessRate=2,47 rxSuccessRate=8,36 targetRoamBSSID=any RSSI=-48
06-10 14:01:18.876 E/WifiStateMachine(560): WifiStateMachine starting scan for "Torradas"WPA_PSK with 2472
06-10 14:01:25.441 I/ValidateNoPeople(560): skipping global notification
06-10 14:01:28.426 I/ValidateNoPeople(560): skipping global notification
06-10 14:01:38.435 I/ValidateNoPeople(560): skipping global notification
06-10 14:01:38.883 E/WifiStateMachine(560): WifiStateMachine CMD_START_SCAN source -2 txSuccessRate=0,31 rxSuccessRate=0,20 targetRoamBSSID=any RSSI=-46
06-10 14:01:38.883 E/WifiStateMachine(560): WifiStateMachine starting scan for "Torradas"WPA_PSK with 2472
06-10 14:01:45.452 I/ValidateNoPeople(560): skipping global notification
06-10 14:01:48.419 I/ValidateNoPeople(560): skipping global notification
06-10 14:01:48.644 I/art     (560): Explicit concurrent mark sweep GC freed 68768(3MB) AllocSpace objects, 1(16KB) LOS objects, 33% free, 26MB/40MB, paused 1.800ms total 192.949ms
06-10 14:01:58.425 I/ValidateNoPeople(560): skipping global notification
06-10 14:01:58.889 E/WifiStateMachine(560): WifiStateMachine CMD_START_SCAN source -2 txSuccessRate=0,31 rxSuccessRate=2,69 targetRoamBSSID=any RSSI=-45
06-10 14:02:05.439 I/ValidateNoPeople(560): skipping global notification
06-10 14:02:08.429 I/ValidateNoPeople(560): skipping global notification
06-10 14:02:09.578 I/PowerManagerService(560): Going to sleep due to screen timeout (uid 1000)...
06-10 14:02:09.755 I/DisplayManagerService(560): Display device changed: DisplayDeviceInfo{"Ecrã Integrado": uniqueId="local:0", 768 x 1280, 60.0 fps, supportedRefreshRates [60.0], density 320, 319.79 x 318.745 dpi, appVsyncOff 0, presDeadline 17666667, touch INTERNAL, rotation 0, type BUILT_IN, state OFF, FLAG_DEFAULT_DISPLAY, FLAG_ROTATES_WITH_CONTENT, FLAG_SECURE, FLAG_SUPPORTS_PROTECTED_BUFFERS}
06-10 14:02:09.759 V/ActivityManager(560): Display changed displayId=0
06-10 14:02:09.766 D/SurfaceFlinger(173): Set power mode=0, type=0 flinger=0xb7997550
06-10 14:02:09.939 D/SurfaceControl(560): Excessive delay in setPowerMode(): 184ms
06-10 14:02:09.942 E/ANDR-PERF-LOCK(196): Failed to apply optimization for resource: 4 level: 0
06-10 14:02:09.943 I/DreamManagerService(560): Entering dreamland.
06-10 14:02:09.944 I/DreamController(560): Starting dream: name=ComponentInfo{com.android.systemui/com.android.systemui.doze.DozeService}, isTest=false, canDoze=true, userId=0
06-10 14:02:09.946 I/PowerManagerService(560): Dozing...
06-10 14:02:09.987 D/AndroidRuntime(9654): Shutting down VM
06-10 14:02:09.987 E/AndroidRuntime(9654): FATAL EXCEPTION: main
06-10 14:02:09.987 E/AndroidRuntime(9654): Process: com.android.systemui, PID: 9654
06-10 14:02:09.987 E/AndroidRuntime(9654): java.lang.NullPointerException: Attempt to invoke virtual method 'void com.android.systemui.doze.ProximitySensorManager.disable(boolean)' on a null object reference
06-10 14:02:09.987 E/AndroidRuntime(9654):  at com.android.systemui.doze.DozeService.listenForSignalsSensor(DozeService.java:413)
06-10 14:02:09.987 E/AndroidRuntime(9654):  at com.android.systemui.doze.DozeService.finishNow(DozeService.java:392)
06-10 14:02:09.987 E/AndroidRuntime(9654):  at com.android.systemui.doze.DozeService.onDreamingStarted(DozeService.java:244)
06-10 14:02:09.987 E/AndroidRuntime(9654):  at android.service.dreams.DreamService$1.run(DreamService.java:1001)
06-10 14:02:09.987 E/AndroidRuntime(9654):  at android.os.Handler.handleCallback(Handler.java:739)
06-10 14:02:09.987 E/AndroidRuntime(9654):  at android.os.Handler.dispatchMessage(Handler.java:95)
06-10 14:02:09.987 E/AndroidRuntime(9654):  at android.os.Looper.loop(Looper.java:135)
06-10 14:02:09.987 E/AndroidRuntime(9654):  at android.app.ActivityThread.main(ActivityThread.java:5274)
06-10 14:02:09.987 E/AndroidRuntime(9654):  at java.lang.reflect.Method.invoke(Native Method)
06-10 14:02:09.987 E/AndroidRuntime(9654):  at java.lang.reflect.Method.invoke(Method.java:372)
06-10 14:02:09.987 E/AndroidRuntime(9654):  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
06-10 14:02:09.987 E/AndroidRuntime(9654):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
06-10 14:02:10.017 D/audio_hw_primary(190): adev_set_parameters: enter: screen_state=off
06-10 14:02:10.020 W/IInputConnectionWrapper(1617): getExtractedText on inactive InputConnection
06-10 14:02:10.023 E/WifiStateMachine(560): cancelDelayedScan -> 507
06-10 14:02:10.026 W/IInputConnectionWrapper(1617): getTextBeforeCursor on inactive InputConnection
06-10 14:02:10.026 E/native  (560): do suspend true
06-10 14:02:10.027 W/IInputConnectionWrapper(1617): getSelectedText on inactive InputConnection
06-10 14:02:10.032 W/IInputConnectionWrapper(1617): getTextAfterCursor on inactive InputConnection
06-10 14:02:10.035 E/bp      (958): onStartInput event aborted: com.touchtype.keyboard.c.ag: could not obtain extracted text (class com.touchtype.keyboard.c.ag)
06-10 14:02:10.039 I/OpenGLRenderer(560): Initialized EGL, version 1.4

**Comment by andrerodrigues86** [comment]
Logcat here:
https://drive.google.com/open?id=0B99H_OcSwaU3eklsekdpc2ZSZkk&authuser=0

**Comment by dexmc** [comment]
@andrerodrigues86 can you reproduce this all the time?

**Comment by andrerodrigues86** [comment]
@dexmc Actually, no. I'm using the phone as usual and everything is working great. When battery reaches 15%, battery saver activates automatically. I just take the phone out of my pocket, double tap to wake and I see the system Ui error message. If I lock it and unlock it doesn't happen...

**Comment by dexmc** [comment]
@andrerodrigues86 ok. 
- Does this happen on the newest build I released a few days ago?
- Did you try a clean flash with the new build?

**Comment by andrerodrigues86** [comment]
@dexmc Yes and yes. I can try and get you some more information. Just tell me what you need.

**Comment by dexmc** [comment]
@andrerodrigues86  try the new build and let me know

**Comment by dexmc** [comment]
@andrerodrigues86 oh if you see the crash again, get me a full log, and share it on pastebin

**Comment by andrerodrigues86** [comment]
Hey! I'm on latest build, clean install. So far so good. I haven't configured everything yet (I use system profiles). I'll let you know if anything happens!

**Comment by Altaf-Mahdi** [comment]
Fixed https://github.com/Euphoria-OS/android_frameworks_base/commit/0112f1a93c05c4c21ca46fba2843e445e6ce489a
