### ISSUE TITLE
QS Task manager bug

### ISSUE THREAD

**Issue by arvind-gr** [Euphoria-OS/Bug-tracker#18]
After Opening task manager, I swipe from bottom to exit it. But next time I open Notification, task manger comes open. Only way to exit it is, I need to press QS icon to exit it. Pressing back is not option there. Consider fixing it...

Device details.,  
Euphoria Mako latest 13062015 built with Quanto kernel

**Comment by dexmc** [comment]
its not a bug. its a feature!
There just isnt an option to close it properly. Its being worked on.
