### ISSUE TITLE
Headphones volume often resets to the "safe volume", apparently at random

### ISSUE THREAD

**Issue by tarockx** [Euphoria-OS/Bug-tracker#2]
Do you use Xposed framework? NO

Your device: Nexus 4 (mako)

Which ROM version are you using? https://www.androidfilehost.com/?fid=23991606952593037

What kernel are you using? DEFAULT

What steps will reproduce the problem?
Seems to happen more or less at random :|

What is the expected result? What do you see instead?
I would expect the headphones volume to be remembered correctly, as it was in old Mahdi rom. 
Instead, it often resets back to about 1/3, which is the maximum allowed if you don't agree to the "safe volume warning" popup.

My proposal: add a "ignore safe volume warnings" option that completely disables this "feature" once and for all.

Is the result seen after a clean flash too? YES

NOTE: I tried to catch a logcat, but unfortunately it's hard due to the fact that the bug appears randomly, or at least I couldn't notice any particular pattern to reproduce it. Sometimes it even happens while I'm listening to music. More often I only notice it after it happens, when I happen to start listening to music again.

**Comment by dexmc** [comment]
Haven't noticed this yet. Will do some thorough testing

**Comment by dexmc** [comment]
this doesnt happen on mine.
