### ISSUE TITLE
Airplane mode does not get disabled after a reboot.

### ISSUE THREAD

**Issue by siddharthbandhu** [Euphoria-OS/Bug-tracker#22]
_Device_: Nexus 4

_ROM version_: Euphoria-OS-1.1-mako-OFFICIAL-20150613 (https://www.androidfilehost.com/?fid=24052804347759350)

_Kernel_: Stock kernel.

_Steps to reproduce the problem_:
1. Long press power button and power menu should appear.
2. Press on Airplane Mode toggle.
3. Reboot your phone by long pressing power button and rebooting.
4. Once it reboots, go to the power menu and try to disable Airplane Mode.

_Expected result_: Airplane mode should disable and cellular activities (call/SMS) should start.

_What you see instead_: The phone shows a no SIM card inserted icon along with the Airplane Mode icon on the status bar. The only way to disable Airplane Mode is by going into Settings, finding the Airplane Mode toggle and disabling it from there.

**Comment by Altaf-Mahdi** [comment]
Tested this on mako and flo and it only seems to be mako that has this problem which makes me think its an aosp issue.
