### ISSUE TITLE
Sleep of death

### ISSUE THREAD

**Issue by slumdog2755** [Euphoria-OS/Bug-tracker#23]
Do you use Xposed framework? No

Device: LGG3 D855 32Go

ROM version: Euphoria-OS-1.1-d855-OFFICIAL-20150623.zip (https://www.androidfilehost.com/?fid=24052804347764077)

Kernel: Stock kernel (3.4.108)

Steps to reproduce the problem:
I have no way to reproduce this bug , it occurs without apparent reason and I do not identify in what situations it happens.

Expected result: .

my phone work ;p

it is an update and I did not try a clean install

**Comment by dsmitty166** [comment]
You need to do a clean flash before I will look into this

**Comment by Altaf-Mahdi** [comment]
@777jon any input on this?

**Comment by jcruz** [comment]
I do not experience this issue on my end. @slumdog2755, I recommend a clean install. If you still encounter this problem I need some logs.

**Comment by Altaf-Mahdi** [comment]
Thanks @777jon I'm going to close this for now.
