### ISSUE TITLE
Not Deleting Frequent Contact

### ISSUE THREAD

**Issue by snehasishj0** [Euphoria-OS/Bug-tracker#24]
Device: Nexus 5

ROM version: Euphoria-OS-1.1-hammerhead-OFFICIAL-20150616

Kernel: Stock kernel.

Steps to reproduce the problem:
1. Remove any frequent contact from frequent contact list.
2. Open Contact list and call any contact.

Observed result: After call, I observed that frequent contacts which I have deleted, restored in frequent contact list.

**Comment by mitchelldavis44** [comment]
I'm confused as to what you're saying, are you meaning that if you swipe away the last called contact and then call another contact the first contact you called is in the last called contact area again?  And just to get out of the way, did you clean flash and are you using xposed?

**Comment by snehasishj0** [comment]
No Mitchell, I am not using xposed and I did clean flash. What I am telling is about frequent contact tiles, not last call contact.  You delete one frequent contact tiles and then dial any other number from contact list. Sorry for confusion. I have attached one dialer image for your understanding, though it is not my dialer screenshot.
Thanks for replying.
![unnamed](https://cloud.githubusercontent.com/assets/13063295/8390715/6947455e-1cc1-11e5-9198-5c30a24bea35.png)

**Comment by snehasishj0** [comment]
I checked with latest build, Euphoria 1.1-hammerhead-official-20150630. Issue still persists. Did you guys understand the problem?

**Comment by Altaf-Mahdi** [comment]
It restores itself because its still a frequent contact and you just called it. Unless you can confirm this doesn't happen in stock I'm closing this for now.

**Comment by snehasishj0** [comment]
No Altaf, I am deleting XYZ from frequent contact tiles and calling ABC which I choose from contact list. And XYZ back in frequent contact tiles. It is working perfectly in stock. If you are deleting XYZ from frequent contact tiles and again calling XYZ, contact should restore to frequent contact. But What if you are not calling XYZ? I think it is a minor one, but it is a issue. Thanks for replying.
