### ISSUE TITLE
Apps disappear from app drawer

### ISSUE THREAD

**Issue by ecydiacruz** [Euphoria-OS/Bug-tracker#25]
After a certain number of apps installed (700+) my apps disappear from the app drawer.  I know its not a specific app because I've tried installing and uninstalling a different set each time but it seems after a certain threshold which I can't pinpoint they all disappear from the app drawer.  The same bug happens no matter what build im running. Im currently running latest build on Nexus 6.

**Comment by dsmitty166** [comment]
Not really sure how to even respond to this.

None of us have no way to replicate this.  We don't have close to that amount of apps.

Do you think 700+ is a bit excessive?

**Comment by ecydiacruz** [comment]
Not when you have 4 kids who all have their own tastes in apps. 

 I can upload titanium backups for someone brave enough to tackle this issue.

**Comment by ecydiacruz** [comment]
Why close the issue?  I've searched Google through an through and still
can't find a solution.  I have no where else to turn too.

**Comment by dsmitty166** [comment]
Have you tried a different launcher? Does this happen on stock?

Without a log or a way to reproduce it to get a log, there's very little hope.

If you want me to be really honest with you, this is a one off case. I don't know of anyone else who would run into this issue. There's a problem when each kid needs 100+ DIFFERENT apps. Not to be a dick, but you can't honestly expect anyone to honestly use many hours trying to locate this, especially without more details. E.g. different launcher, stock behavior, logs

**Comment by ecydiacruz** [comment]
It's every launcher including stock and I will be happy to provide
reproduce the issue and supply you or anybody with before and after logs as
well as a list of installed apps and/or a zip of my titanium backups for
anyone who's willing to try.

By the way I've tried doing a clean install on numerous builds.  Frankly, I
think this is a larger issue at hand with lollypop which Google doesn't
want to address.

Please help

**Comment by dsmitty166** [comment]
So this happens on stock ROM too?

**Comment by ecydiacruz** [comment]
I will make a nandroid back up of euphoria and try tonight.
