### ISSUE TITLE
System profiles triggering broken on latest mako build

### ISSUE THREAD

**Issue by eurochild-dps** [Euphoria-OS/Bug-tracker#26]
both with the built-in wifi triggering and also causing a crash in a plugin app called "cm profiles" i use in tasker to activate profiles
- tested on both dirty and clean flash

**Comment by dexmc** [comment]
Logcat please

**Comment by dexmc** [comment]
@Altaf-Mahdi Its probably the new cmsdk profile commits. Can you take a look

**Comment by eurochild-dps** [comment]
https://www.dropbox.com/s/drfp86ubcetxt9c/log-builtin-trigger.txt?dl=0
https://www.dropbox.com/s/3f6l15xnhvregm1/log-tasker.txt?dl=0

**Comment by cap67** [comment]
Same in 06.30 shamu build, wifi trigger won't work.

**Comment by eurochild-dps** [comment]
this might be the solution idk
http://review.cyanogenmod.org/#/c/102184/

**Comment by Altaf-Mahdi** [comment]
@eurochild-dps thanks that is the fix, I'll be pushing it soon.

**Comment by Altaf-Mahdi** [comment]
Fixed https://github.com/Euphoria-OS-Legacy/cm_platform_sdk/commit/b168822537ea9d5ba8a6ed8c3647d707b7efe41c
