### ISSUE TITLE
Option to hide search bar on the recents/multitasking menu is not working 

### ISSUE THREAD

**Issue by krugdenis** [Euphoria-OS/Bug-tracker#28]
Do you use Xposed framework? If yes, do not even bother reporting.
Xposed is not installed

Your device: hammerhead

Which ROM version are you using? (provide download link)
https://www.androidfilehost.com/?fid=24052804347767060
What kernel are you using - included in the ROM or from another source?
Included in the rom

What steps will reproduce the problem?
1. Open settings-multitasking and select to hide search bar
2. Open recents/multitasking menu, look at the search bar
3. Search bar is not hidden, it's where it was before

What is the expected result? What do you see instead?
Search bar in the recents/multitasking menu must be hidden
Is the result seen after a clean flash too?
Yes
Attach a logcat and/or a last_kmsg . Without this,the issue is impossible
to fix.

**Comment by mitchelldavis44** [comment]
Confirmed on hammerhead.

**Comment by dexmc** [comment]
its broken on mako too.

**Comment by Altaf-Mahdi** [comment]
Fixed https://github.com/Euphoria-OS/android_packages_apps_Settings/commit/4e4e356db2bf290544a5a89176ef8ca4d467540e
