### ISSUE TITLE
Unlinking volume level issues

### ISSUE THREAD

**Issue by droidkevlar** [Euphoria-OS/Bug-tracker#3]
Do you use Xposed framework? If yes, do not even bother reporting.
Uninstall Xposed(&reboot), check if the bug you're trying to report still
exists and then proceed. Otherwise,your report will be declared invalid.

No

Your device: Nexus 6 (Moto purchased)

Which ROM version are you using? (provide download link)
http://euphoria-os.ninja/download.php?file=Nexus%206/Nexus%206%20Builds/Euphoria-OS-1.1-shamu-20150502.zip

What kernel are you using - included in the ROM or from another source?
(provide xda/download link)
http://forum.xda-developers.com/nexus-6/development/kernel-fk-wake-gestures-t3060196
https://onedrive.live.com/?cid=c666ac25583e4123&id=c666ac25583e4123%212157&ithint=folder,img&authkey=!ALdlunB7YTplo4Q

What steps will reproduce the problem?
1. Unlink notification & volume levels
2. Change notification volume level
3. Change ringer volume level

What is the expected result? What do you see instead?
Should keep them unlinked. It brings them to the same volume levels. 

Is the result seen after a clean flash too?
Yes, this is coming from 100% clean install with 0 apps installed.

Attach a logcat and/or a last_kmsg . Without this,the issue is impossible
to fix.

**Comment by dsmitty166** [comment]
Confirmed.

Can any other devices test this please.

Only changing ring volume seems to link these, not notification

**Comment by ghost** [comment]
Confirmed on my VZW Nexus 6.

**Comment by dexmc** [comment]
@dsmitty166  Confirmed on nexus4

**Comment by dexmc** [comment]
this is fixed thanks to a commit from cm. Tested working.

**Comment by droidkevlar** [comment]
Is this on todays build or will it be pushed to next build?

**Comment by dexmc** [comment]
next build.
