### ISSUE TITLE
msm_iommu: Unexpected IOMMU page fault!

### ISSUE THREAD

**Issue by chenshaoju** [Euphoria-OS/Bug-tracker#32]
Sorry for my English,This issue look's like memory leak or something else.

Do you use Xposed framework? If yes, do not even bother reporting.
Uninstall Xposed(&reboot), check if the bug you're trying to report still
exists and then proceed. Otherwise,your report will be declared invalid.
No,I'm Not install Xposed.

Your device:
Google Nexus 4 16GB

Which ROM version are you using? (provide download link)
Euphoria 1.1-mako-OFFICIAL-20150630
https://plus.google.com/117421397767192393992/posts/PXhFnHHKTKa

What kernel are you using - included in the ROM or from another source?
(provide xda/download link)
3.4.0-Mako
Euphoria-OS@Nexus 4 #1 
Mon Jun 29 22:45:01 PDT 2015
https://plus.google.com/117421397767192393992/posts/PXhFnHHKTKa

What steps will reproduce the problem?
1.Keep phone on least 100 Hours(Not screen on)
2.Play any video in VLC by use hardware acceleration.
3.A small chance,The phone will freeze and auto-reboot in 1~2 min.

What is the expected result? What do you see instead?
Normal video play.

Is the result seen after a clean flash too?
Upgrade from Euphoria-OS-1.1-mako-OFFICIAL-20150613.zip by only erase /system

Attach a logcat and/or a last_kmsg . Without this,the issue is impossible
to fix.
last_kmsg: http://pastebin.com/UfbgJAPT

**Comment by dexmc** [comment]
1. The phone is 3 years old.
2. Stock android isn't perfect.
3. We do not have time to look at bugs which have a "small chance" of occurring. Priorities, you know.
4. We seldom touch anything related to media playback. If this is really an issue, it has to happen on stock android and/or any other rom out there too.

I use MX player and haven't seen a reboot in like ever.

**Comment by chenshaoju** [comment]
Sad...But thanks anyway.  :)
