### ISSUE TITLE
Whats App does not work over mobile data

### ISSUE THREAD

**Issue by vikky1912** [Euphoria-OS/Bug-tracker#36]
Whats App does not work over mobile data in the following rom:

Euphoria-OS-1.1-shamu-OFFICIAL-20150701.zip
http://euphoria-os.ninja/download.php?file=Nexus%206/Nexus%206%20Builds/Euphoria-OS-1.1-shamu-OFFICIAL-20150701.zip

**Comment by dsmitty166** [comment]
This is an app problem I'm assuming, or you need to clean flash

**Comment by dsmitty166** [comment]
I just installed it, working fine for me

**Comment by vikky1912** [comment]
i did a clean flash, but i am same issue 20150701 and above rom version..

**Comment by dsmitty166** [comment]
Did you restore apps after the flash? 

Like I said, I just installed it. Working fine.

Can you explain what's not working, how to reproduce it? You have given very little detail

**Comment by vikky1912** [comment]
1.Whats app is not able connect to internet over mobile data: i am not able to send any messages
2.It works fine over wifi
3.i did a clean flash re installed rom,  re installed whatsapp, cleared cache, issue persisits.
4.I did the testing for following rom:
   Euphoria-OS-1.1-shamu-OFFICIAL-20150628.zip
   Euphoria-OS-1.1-shamu-OFFICIAL-20150630.zip
   Euphoria-OS-1.1-shamu-OFFICIAL-20150701.zip
5.In all the above rom version issue persists however in 
   Euphoria-OS-1.1-shamu-OFFICIAL-20150624.zip rom version it works fine
6.Currently testing Euphoria-OS-1.1-shamu-OFFICIAL-20150718.zip
will get back to you on that.

Thank you for quick reply. Awesome rom by the way.

**Comment by vikky1912** [comment]
Other than whats app i am able to access internet over every other app.

It might be something related to carrier settings. I did go through change log i did not find anything related to this change.

**Comment by tarockx** [comment]
Your carrier might simply be blocking it. 
One way to find out : flash stock rom and try.
