### ISSUE TITLE
Privacy Guard settings disappeared with last update 20150718

### ISSUE THREAD

**Issue by keilunsoftware** [Euphoria-OS/Bug-tracker#37]
Steps to reproduce it:
Flash ROM 20150701 - fresh install.
Update to 20150718 - Privacy Guard advanced options disappear (see attached screenshot for the "disappear" meaning).
![screenshot_2015-07-22-16-18-18](https://cloud.githubusercontent.com/assets/10826741/8827552/aba96622-308d-11e5-88e8-b3485879553b.png)

**Comment by dexmc** [comment]
Its just you. Do a clean flash of 0718.
