### ISSUE TITLE
ROM Updater says out of date, but is latest

### ISSUE THREAD

**Issue by droidkevlar** [Euphoria-OS/Bug-tracker#4]
Do you use Xposed framework? No

Your device: Nexus 6 (Moto purchase)

Which ROM version are you using? (provide download link)
http://euphoria-os.ninja/download.php?file=Nexus%206/Nexus%206%20Builds/Euphoria-OS-1.1-shamu-OFFICIAL-20150512.zip

What kernel are you using - included in the ROM or from another source? Stock kernel w/ ROM

What steps will reproduce the problem?
1. Dirty flash Euphoria-OS-1.1-shamu-OFFICIAL-20150512.zip over Euphoria-OS-1.1-shamu-20150502.zip
2. Reboot phone
3. Let sit for a few mins

What is the expected result? What do you see instead?
Nothing. Keep getting told is not latest version. 

Is the result seen after a clean flash too?
Did not try. 

Attach a logcat and/or a last_kmsg . Without this,the issue is impossible
to fix.

**Comment by dsmitty166** [comment]
Yeah I need to fix the ota center, since we are now using official/unofficial flags. I didn't get this in testing of course, but I couldn't test proper without the server. I'll look into it.

**Comment by dsmitty166** [comment]
I have fixed this now, expect a new build shortly
