### ISSUE TITLE
Ambient Display pulse's when disabled

### ISSUE THREAD

**Issue by droidkevlar** [Euphoria-OS/Bug-tracker#6]
Do you use Xposed framework? No

Your device: Nexus 6

Which ROM version are you using?
http://euphoria-os.ninja/download.php?file=Nexus%206/Nexus%206%20Builds/Euphoria-OS-1.1-shamu-OFFICIAL-20150512.zip

What kernel are you using - included in the ROM or from another source?
http://forum.xda-developers.com/nexus-6/development/kernel-fk-wake-gestures-t3060196
https://onedrive.live.com/?cid=c666ac25583e4123&id=c666ac25583e4123%212157&ithint=folder,img&authkey=!ALdlunB7YTplo4Q

What steps will reproduce the problem?
1. Have Ambient enabled
2. Do not enable overwrite value

What is the expected result? What do you see instead?
Ambient display to show normal. Ambient comes on to show message, goes away, 5-15s later, shows again. Does over and over for about30-60s 
**Also noticed if I do not wake device after letting it do this, ambient does not work until I clear all items (If should open another bug, please let me know and I will)**

Is the result seen after a clean flash too?
Yes

Attach a logcat and/or a last_kmsg . Without this,the issue is impossible
to fix. 

Do not have logcat, but works as supposed to on Terminus ROM if that helps.

**Comment by dexmc** [comment]
works fine on mako.

@dsmitty166 
Dave, can you take a look

**Comment by dsmitty166** [comment]
So you're saying that ambient display works when it's disabled?  Your title and issue steps conflict with each other

**Comment by droidkevlar** [comment]
No. Im saying when you have pulse disabled, it still pulses.
