### ISSUE TITLE
Google now everywhere settings not stocking after reboot

### ISSUE THREAD

**Issue by aliminator** [Euphoria-OS/Bug-tracker#7]
Do you use Xposed framework? No

Your device: Nexus 6

Which ROM version are you using?
http://euphoria-os.ninja/download.php?file=Nexus%206/Nexus%206%20Builds/Euphoria-OS-1.1-shamu-OFFICIAL-20150514.zip

What kernel are you using - included in the ROM or from another source?
Included.

What steps will reproduce the problem?
1. Settings -> Language and Input -> Voice Input -> Enhanced Google Services -> "Ok Google" detection
2. Always on and Personal results options are disabled.
3. Switch from Enhance Google Services to Basic Google Services and then back.
4. Always on and Personal results options are enabled now.
5. Reboot.
6.Always on and Personal results options are disabled again.

What is the expected result? What do you see instead?
Always on and Personal results options should always be enabled.

Is the result seen after a clean flash too?
Yes

Attach a logcat and/or a last_kmsg . Without this,the issue is impossible
to fix.
Dont have logcat.

**Comment by dsmitty166** [comment]
This would be an issue with the gapps you're using. Just tested it, enabled always on and rebooted. Its still on.

**Comment by aliminator** [comment]
Can you please let me know which gapps you are using? Appreciate it!

**Comment by dsmitty166** [comment]
I run banks gapps only

**Comment by aliminator** [comment]
Confirmed working with 5-14 build of rom + bank gapps 5-14 + clean flash. Thanks.

**Comment by aliminator** [comment]
Spoke too soon. Its disabled again after a few restarts. Not sure what triggered it.

**Comment by dsmitty166** [comment]
I have been through countless flashes and reboots in the last few days and mine still works just fine.

Clean flash with banks

**Comment by g2uzer** [comment]
Hey dsmitty, in using banks GappsL5-1-15 and have this issue as well. What version of gapps are you using ?

**Comment by dsmitty166** [comment]
I'm on an old version of Gapps, from April sometime. Again, it's still enabled here.  I'm closing this, as it's 100% Gapps related.  If they new banks gapps don't work, then try some others
