### ISSUE TITLE
phone rebooted 

### ISSUE THREAD

**Issue by pantmunu** [Euphoria-OS/Bug-tracker#8]
So I changed the DPI to 520 and let the ohn reboot.  After few minutes the had a sod followed by a reboot.  I'm all stock.  Nexus 6 .

**Comment by pantmunu** [comment]
How do I post the last kmesg here.  Its quite large.

**Comment by pantmunu** [comment]
0:msm_cpu_pm_enter_sleep mode:3 during suspend
[ 6548.310521] Resume caused by IRQ 430, mxhci_hsic_wakeup
[ 6548.310521] Resume caused by IRQ 200, qcom,smd-rpm
[ 6548.310521] Resume caused by IRQ 203, fc4281d0.qcom,mpm
[ 6548.310521] Resume caused by IRQ 240, msmgpio
[ 6548.310521] Suspended for 0.000 seconds
[ 6548.311586] Enabling non-boot CPUs ...
[ 6548.313760] Renew affinity for 1455 processes to cpu 1
[ 6548.314320] CPU1 is up
[ 6548.316071] Renew affinity for 1454 processes to cpu 2
[ 6548.316538] CPU2 is up
[ 6548.318060] Renew affinity for 1454 processes to cpu 3
[ 6548.318621] CPU3 is up
[ 6548.320585] msm_pcie_enable: msm_pcie_enable: PCIe: Assert the reset of endpoint of RC0.
[ 6548.331696] msm_pcie_enable: msm_pcie_enable: PCIe RC0 PHY is ready!
[ 6548.345352] msm_pcie_enable: msm_pcie_enable: PCIe: Release the reset of endpoint of RC0.
[ 6548.372222] msm_pcie_enable: msm_pcie_enable: PCIe RC0 link initialized
[ 6548.392682] PM: noirq resume of devices complete after 74.025 msecs
[ 6548.397234] PM: early resume of devices complete after 3.403 msecs
[ 6548.528422] PM: resume of devices complete after 131.132 msecs
[ 6548.534937] Restarting tasks ... done.
[ 6548.546168] PM: suspend exit 2015-05-15 21:45:01.709776872 UTC
[ 6548.725635] PM: suspend entry 2015-05-15 21:45:01.889261455 UTC
[ 6548.725657] PM: Syncing filesystems ... done.
[ 6548.800837] Freezing user space processes ... [ 6548.801588] Error: returning -512 value

[ 6548.805473] last active wakeup source: ipc0000010b_sensors.qcom
[ 6548.805549] 
[ 6548.805597] Freezing of tasks aborted after 0.004 seconds (230 tasks refusing to freeze, wq_busy=0):
[ 6548.805622] 
[ 6548.805643] Restarting tasks ... done.
[ 6548.810147] PM: suspend exit 2015-05-15 21:45:01.973761768 UTC
[ 6548.910881] PM: suspend entry 2015-05-15 21:45:02.074482393 UTC
[ 6548.910927] PM: Syncing filesystems ... done.
[ 6549.022370] Freezing user space processes ... [ 6549.023806] Error: returning -512 value
(elapsed 0.011 seconds) done.
[ 6549.034004] Freezing remaining freezable tasks ... (elapsed 0.005 seconds) done.
[ 6549.039680] Suspending console(s) (use no_console_suspend to debug)
[ 6549.048437] usb 1-1: abort suspend
[ 6549.048515] dpm_run_callback(): usb_dev_suspend+0x0/0x1c returns -16
[ 6549.048560] PM: Device 1-1 failed to suspend async: error -16
[ 6549.048627] PM: Some devices failed to suspend
[ 6549.050339] PM: resume of devices complete after 1.673 msecs
[ 6549.057711] Restarting tasks ... done.
[ 6549.066999] PM: suspend exit 2015-05-15 21:45:02.230601351 UTC
[ 6549.167998] PM: suspend entry 2015-05-15 21:45:02.331594945 UTC
[ 6549.168055] PM: Syncing filesystems ... done.
[ 6549.261855] Freezing user space processes ... [ 6549.263289] Error: returning -512 value
(elapsed 0.011 seconds) done.
[ 6549.273645] Freezing remaining freezable tasks ... (elapsed 0.005 seconds) done.
[ 6549.279309] Suspending console(s) (use no_console_suspend to debug)
[ 6549.287945] usb 1-1: abort suspend
[ 6549.288012] dpm_run_callback(): usb_dev_suspend+0x0/0x1c returns -16
[ 6549.288042] PM: Device 1-1 failed to suspend async: error -16
[ 6549.288110] PM: Some devices failed to suspend
[ 6549.289389] PM: resume of devices complete after 1.244 msecs
[ 6549.296731] Restarting tasks ... done.
[ 6549.305944] PM: suspend exit 2015-05-15 21:45:02.469544163 UTC
[ 6549.406610] PM: suspend entry 2015-05-15 21:45:02.570205674 UTC
[ 6549.406665] PM: Syncing filesystems ... done.
[ 6549.468741] Freezing user space processes ... [ 6549.469859] Error: returning -512 value
(elapsed 0.009 seconds) done.
[ 6549.478104] Freezing remaining freezable tasks ... (elapsed 0.004 seconds) done.
[ 6549.482619] Suspending console(s) (use no_console_suspend to debug)
[ 6549.489320] usb 1-1: abort suspend
[ 6549.489383] dpm_run_callback(): usb_dev_suspend+0x0/0x1c returns -16
[ 6549.489427] PM: Device 1-1 failed to suspend async: error -16
[ 6549.489481] PM: Some devices failed to suspend
[ 6549.490831] PM: resume of devices complete after 1.318 msecs
[ 6549.496805] Restarting tasks ... done.
[ 6549.503762] PM: suspend exit 2015-05-15 21:45:02.667369424 UTC
[ 6549.604657] PM: suspend entry 2015-05-15 21:45:02.768253851 UTC
[ 6549.604709] PM: Syncing filesystems ... done.
[ 6549.693596] Freezing user space processes ... [ 6549.694871] Error: returning -512 value
(elapsed 0.010 seconds) done.
[ 6549.704377] Freezing remaining freezable tasks ... (elapsed 0.005 seconds) done.
[ 6549.709590] Suspending console(s) (use no_console_suspend to debug)
[ 6549.717747] usb 1-1: abort suspend
[ 6549.717818] dpm_run_callback(): usb_dev_suspend+0x0/0x1c returns -16
[ 6549.717861] PM: Device 1-1 failed to suspend async: error -16
[ 6549.717915] PM: Some devices failed to suspend
[ 6549.719410] PM: resume of devices complete after 1.459 msecs
[ 6549.725985] Restarting tasks ... done.
[ 6549.735087] PM: suspend exit 2015-05-15 21:45:02.898686872 UTC
[ 6549.836476] PM: suspend entry 2015-05-15 21:45:03.000067392 UTC
[ 6549.836539] PM: Syncing filesystems ... done.
[ 6549.892854] Freezing user space processes ... [ 6549.893785] Error: returning -512 value
(elapsed 0.007 seconds) done.
[ 6549.900454] Freezing remaining freezable tasks ... (elapsed 0.003 seconds) done.
[ 6549.903873] Suspending console(s) (use no_console_suspend to debug)
[ 6549.908613] usb 1-1: abort suspend
[ 6549.908650] dpm_run_callback(): usb_dev_suspend+0x0/0x1c returns -16
[ 6549.908663] PM: Device 1-1 failed to suspend async: error -16
[ 6549.908711] PM: Some devices failed to suspend
[ 6549.909670] PM: resume of devices complete after 0.942 msecs
[ 6549.913127] Restarting tasks ... done.
[ 6549.919503] PM: suspend exit 2015-05-15 21:45:03.083125517 UTC
[ 6550.020266] PM: suspend entry 2015-05-15 21:45:03.183880778 UTC
[ 6550.020304] PM: Syncing filesystems ... done.
[ 6550.071522] Freezing user space processes ... [ 6550.072636] Error: returning -512 value
(elapsed 0.008 seconds) done.
[ 6550.080517] Freezing remaining freezable tasks ... (elapsed 0.004 seconds) done.
[ 6550.084904] Suspending console(s) (use no_console_suspend to debug)
[ 6550.091474] usb 1-1: abort suspend
[ 6550.091531] dpm_run_callback(): usb_dev_suspend+0x0/0x1c returns -16
[ 6550.091572] PM: Device 1-1 failed to suspend async: error -16
[ 6550.091624] PM: Some devices failed to suspend
[ 6550.092822] PM: resume of devices complete after 1.165 msecs
[ 6550.098635] Restarting tasks ... done.
[ 6550.105981] PM: suspend exit 2015-05-15 21:45:03.269588226 UTC
[ 6550.206870] PM: suspend entry 2015-05-15 21:45:03.370473017 UTC
[ 6550.206915] PM: Syncing filesystems ... done.
[ 6550.260168] Freezing user space processes ... [ 6550.261422] Error: returning -512 value
(elapsed 0.010 seconds) done.
[ 6550.270464] Freezing remaining freezable tasks ... (elapsed 0.005 seconds) done.
[ 6550.275676] Suspending console(s) (use no_console_suspend to debug)
[ 6550.283312] usb 1-1: abort suspend
[ 6550.283373] dpm_run_callback(): usb_dev_suspend+0x0/0x1c returns -16
[ 6550.283402] PM: Device 1-1 failed to suspend async: error -16
[ 6550.283543] PM: Some devices failed to suspend
[ 6550.285041] PM: resume of devices complete after 1.460 msecs
[ 6550.292095] Restarting tasks ... done.
[ 6550.301182] PM: suspend exit 2015-05-15 21:45:03.464785205 UTC
[ 6550.402244] PM: suspend entry 2015-05-15 21:45:03.565837236 UTC
[ 6550.402301] PM: Syncing filesystems ... done.
[ 6550.458773] Freezing user space processes ... [ 6550.459821] Error: returning -512 value
(elapsed 0.008 seconds) done.
[ 6550.467149] Freezing remaining freezable tasks ... (elapsed 0.004 seconds) done.
[ 6550.471424] Suspending console(s) (use no_console_suspend to debug)
[ 6550.477672] usb 1-1: abort suspend
[ 6550.477708] dpm_run_callback(): usb_dev_suspend+0x0/0x1c returns -16
[ 6550.477722] PM: Device 1-1 failed to suspend async: error -16
[ 6550.477842] PM: Some devices failed to suspend
[ 6550.478801] PM: resume of devices complete after 0.929 msecs
[ 6550.484197] Restarting tasks ... done.
[ 6550.490472] PM: suspend exit 2015-05-15 21:45:03.654083746 UTC
[ 6550.591360] PM: suspend entry 2015-05-15 21:45:03.754963486 UTC
[ 6550.591408] PM: Syncing filesystems ... done.
[ 6550.640408] Freezing user space processes ... [ 6550.641264] Error: returning -512 value
(elapsed 0.007 seconds) done.
[ 6550.647508] Freezing remaining freezable tasks ... (elapsed 0.003 seconds) done.
[ 6550.651242] Suspending console(s) (use no_console_suspend to debug)
[ 6550.656369] usb 1-1: abort suspend
[ 6550.656424] dpm_run_callback(): usb_dev_suspend+0x0/0x1c returns -16
[ 6550.656462] PM: Device 1-1 failed to suspend async: error -16
[ 6550.656522] PM: Some devices failed to suspend
[ 6550.657722] PM: resume of devices complete after 1.170 msecs
[ 6550.663286] Restarting tasks ... done.
[ 6550.669205] PM: suspend exit 2015-05-15 21:45:03.832815413 UTC
[ 6550.770151] PM: suspend entry 2015-05-15 21:45:03.933747548 UTC
[ 6550.770206] PM: Syncing filesystems ... done.
[ 6550.822061] Freezing user space processes ... [ 6550.823092] Error: returning -512 value
(elapsed 0.008 seconds) done.
[ 6550.830461] Freezing remaining freezable tasks ... (elapsed 0.003 seconds) done.
[ 6550.834389] Suspending console(s) (use no_console_suspend to debug)
[ 6550.840265] usb 1-1: abort suspend
[ 6550.840311] dpm_run_callback(): usb_dev_suspend+0x0/0x1c returns -16
[ 6550.840346] PM: Device 1-1 failed to suspend async: error -16
[ 6550.840390] PM: Some devices failed to suspend
[ 6550.841403] PM: resume of devices complete after 0.988 msecs
[ 6550.846130] Restarting tasks ... done.
[ 6550.852343] PM: suspend exit 2015-05-15 21:45:04.015962392 UTC
[ 6550.952931] PM: suspend entry 2015-05-15 21:45:04.116539267 UTC
[ 6550.952974] PM: Syncing filesystems ... done.
[ 6550.997920] Freezing user space processes ... [ 6550.998848] Error: returning -512 value
(elapsed 0.007 seconds) done.
[ 6551.005480] Freezing remaining freezable tasks ... (elapsed 0.003 seconds) done.
[ 6551.008938] Suspending console(s) (use no_console_suspend to debug)
[ 6551.034812] D2H_MB_DATA: D3 ACK
[ 6551.067384] msm_pcie_disable: msm_pcie_disable: PCIe: Assert the reset of endpoint of RC0.
[ 6551.094222] PM: suspend of devices complete after 81.831 msecs
[ 6551.097667] PM: late suspend of devices complete after 3.425 msecs
[ 6551.103278] PM: noirq suspend of devices complete after 5.593 msecs
[ 6551.103291] Disabling non-boot CPUs ...
[ 6551.107711] Renew affinity for 1455 processes to cpu 1
[ 6551.112673] Renew affinity for 1455 processes to cpu 2
[ 6551.117458] Renew affinity for 1455 processes to cpu 3
[ 6551.118948] CPU0:msm_cpu_pm_enter_sleep mode:3 during suspend
[ 6551.118948] Resume caused by IRQ 439, atmel_mxt_ts
[ 6551.118948] Resume caused by IRQ 200, qcom,smd-rpm
[ 6551.118948] Resume caused by IRQ 203, fc4281d0.qcom,mpm
[ 6551.118948] Resume caused by IRQ 240, msmgpio
[ 6551.118948] Suspended for 0.000 seconds
[ 6551.119775] Enabling non-boot CPUs ...
[ 6551.121942] Renew affinity for 1455 processes to cpu 1
[ 6551.122394] CPU1 is up
[ 6551.123602] Renew affinity for 1454 processes to cpu 2
[ 6551.123904] CPU2 is up
[ 6551.125189] Renew affinity for 1454 processes to cpu 3
[ 6551.125668] CPU3 is up
[ 6551.127174] msm_pcie_enable: msm_pcie_enable: PCIe: Assert the reset of endpoint of RC0.
[ 6551.137672] msm_pcie_enable: msm_pcie_enable: PCIe RC0 PHY is ready!
[ 6551.155245] msm_pcie_enable: msm_pcie_enable: PCIe: Release the reset of endpoint of RC0.
[ 6551.182086] msm_pcie_enable: msm_pcie_enable: PCIe RC0 link initialized
[ 6551.202035] PM: noirq resume of devices complete after 76.338 msecs
[ 6551.208614] PM: early resume of devices complete after 4.378 msecs
[ 6551.325904] PM: resume of devices complete after 117.229 msecs
[ 6551.332038] Restarting tasks ... done.
[ 6551.344507] PM: suspend exit 2015-05-15 21:45:51.782837321 UTC
[ 6551.445408] PM: suspend entry 2015-05-15 21:45:51.883738467 UTC
[ 6551.445455] PM: Syncing filesystems ... done.
[ 6551.500157] Freezing user space processes ... [ 6551.501207] Error: returning -512 value
(elapsed 0.008 seconds) done.
[ 6551.508382] Freezing remaining freezable tasks ... (elapsed 0.004 seconds) done.
[ 6551.512634] Suspending console(s) (use no_console_suspend to debug)

Sorry for the long long long log.

**Comment by dexmc** [comment]
please use pastebin next time. There are tons of text upload sites.

also, did you try reproducing it ? If this is a one off, im closing this.

**Comment by dsmitty166** [comment]
Agree Dex, If it can't be reproduced, there's not much I can do

**Comment by dexmc** [comment]
No worries. Just needed you to look at the log. Let's see if he can reproduce, or I'll go ahead and close it

**Comment by pantmunu** [comment]
Sorry guys ..for the delay.  No.  Actually.  After that reboot .. I haven't been able to reproduce it.  Prolly something wrong on the user end. If it happens again .. I'll come fully prepared.  
Thanks.
